// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  home_hero: dynamic(() => import("./HomeHero")),
  rich_text: dynamic(() => import("./RichText")),
};
